name: run_tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: install_uv
        run: pip install uv
      - name: install_dependencies
        run: uv pip install -e .
      - name: install_pytest
        run: uv pip install pytest
      - name: run_tests
        run: pytest
